name: ${project.name}
main: net.daboross.bukkitdev.undergroundmayhem.UndergroundMayhemPlugin
version: ${project.version}
description: ${project.description}
url: ${project.url}
author: Dabo Ross
load: startup