name: ${project.name}
main: net.daboross.bukkitdev.mayhem.MayhemPlugin
version: ${project.version}
description: ${project.description}
url: ${project.url}
author: Dabo Ross
load: startup
commands:
  mayhem: